dist: trusty
language: node_js
node_js:
  - 8
  - 6
  - 4

before_install:
  - yarn global add greenkeeper-lockfile@1
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install

before_script: greenkeeper-lockfile-update
script: npm run build
# Only the node version 6 job will upload the lockfile
after_script: greenkeeper-lockfile-upload

after_success:
  - npm run-script doc
  - echo 'node_modules' > .gitignore
  - cp node_modules/openlayers/dist/ol-debug.js dist/ol-debug.js
  - echo $CNAME > CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  node: '8'
